### ISSUE TITLE
What's the goal of this project?

### ISSUE THREAD

**Issue by nbro** [nbro/understanding-math#3]
A few questions and sentences which may help to better define the goal of this project:

0. What's the goal of this project? Why does it exist? What does "understanding of mathematics" even mean?

1. Who's the target audience of this project? 

    - So far, this repository seems useful only to people with a decent mathematical education, i.e. high-school or higher.

3. Which topics **should** or **not** be covered, i.e. which topics are related to the understanding of mathematics?

4. Topics covered so far
    
      - [x] Notation
      - [x] Formulas
          - How are formulas different from notation?
       - [x] Terminology
       - [x] "Mathematical language"
            - What is it, btw?
       - [x] Proofs
       - [x] "Understanding mathematics"
           - Resources without a more specific categorization. 
       - [ ] Problem-solving
           - There are already links which point to resources related to this topic, but are not under a category or section called problem-solving.

5. Which links should be included? 

   1. Should we include links only to online immediately and freely accessible resources or can we also have links to websites like Amazon?

6. Should this project include sections for sub-areas of mathematics?

7. Should this project include an advanced searching tool to facilitate its users to obtain a resource (to satisfy their needs) as fast as possible?

8. Is this project also concerned with the history of mathematics in the context of understanding it (e.g. history of mathematical notation, terminology, etc)?

9. What about websites like [https://math.stackexchange.com](https://math.stackexchange.com)?

**Comment by shxdow** [comment]
@nbro I feel as if the purpose of this project is pretty clear: a list of resources aimed at helping people wanting to improve their approach to mathematics and related fields. A clear and concise sentence at the top of the page should do more than enough.
